config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :customers, :controllers => { registrations: 'registrations' }
  get 'operations/new_deposit', to: 'operations#new_deposit', as: "deposit"
  post 'operations/new_deposit', to: 'operations#create_deposit'
  get 'operations/new_withdraw', to: 'operations#new_withdraw', as: "withdraw"
  post 'operations/new_withdraw', to: 'operations#create_withdraw'
  get 'operations/new_transfer', to: 'operations#new_transfer', as: "transfer"
  post 'operations/new_transfer', to: 'operations#create_transfer'
  resources :operations, only: [:show, :index] do
    collection do
      match 'search' => 'operations#search', via: [:get, :post], as: :search
    end
  end
  resources :accounts, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :customer
  
  validates_presence_of :account_number, :balance, :customer_id
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
  validates_format_of :account_number, with: /\A.[0-9]+\z/
  validates_length_of :account_number, in: 4..8 

  before_validation :load_standart

  def load_standart
    if self.new_record?
      self.account_number = (SecureRandom.random_number * (10**5)).round
      self.balance = 0.0
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account
  validates_presence_of :email, :first_name, :last_name, :cpf, :address, :rg, :password
  validates_uniqueness_of :email, :cpf
  validates_format_of :email, with: EMAIL_FORMAT
  validates_format_of :cpf, with: /\A.[0-9]+\z/
  validates_length_of :cpf, is: 11


  def full_name
    "#{first_name} #{last_name}" 
  end
  
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :account
  KIND = %w[withdraw deposit transfer]
  validates_presence_of :account, :amount, :interest_rate
  validates :kind, presence: true, inclusion: { in: KIND }
  validate :check_withdraw
  validates :amount, numericality: { greater_than: 0 }

  private

  def check_withdraw
    errors.add(:amount, 'Not enough balance in account!') if kind == "withdraw" && amount > account.balance
  end 

  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.find(params[:id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_customer!
  layout 'search', only: [:index, :search] 
  
  def index
    @search = Operation.search(params[:q])
    @pagy, @operations = pagy(@search.result.where(account_id: current_customer.account))
  end

  def search
    index
    render :index
  end
  
  
 
  def show
    @operation = Operation.find(params[:id])
  end
  
  def new_deposit
   @operation = Operation.new
   @account = current_customer.account
   @kind = "deposit"
   @interest_rate = 0
  end

  def create_deposit
    @errors = ValidationOperationService.new(operations_params).execute!
    if @errors.empty?
      @operation = OperationService.new(operations_params).execute!
      redirect_to @operation
    else
      redirect_to :new_deposit
    end
  end

  def new_withdraw
    @operation = Operation.new
    @account = current_customer.account
    @kind = "withdraw"
    @interest_rate = 0
  end

  def create_withdraw
    @errors = ValidationOperationService.new(operations_params).execute!
    if @errors.empty?
      @operation = OperationService.new(operations_params).execute!
      redirect_to @operation
    else
      redirect_to "new_withdraw"
    end
  end

  def new_transfer
    @operation = Operation.new
    @account = current_customer.account
    @kind = "transfer"
  end

  def create_transfer
    @errors = ValidationOperationService.new(operations_params).execute!
    if @errors.empty?
      @operation = OperationService.new(operations_params).execute!
      redirect_to @operation
    else
      redirect_to "new_transfer"#json: {errors: @errors}, status: 402 if @errors.size > 0 
    end
  end

  private
  def operations_params
    params.require(:operation).permit(:account_id, :kind, :recipient, :amount, :interest_rate)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
    if @customer.save
      customer = Customer.last
      Account.create!(customer: customer)  
    end
  end
  

  private

  def sign_up_params
    params.require(:customer).permit(:first_name, :last_name, :email, :rg, :cpf, :address, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:customer).permit(:first_name, :last_name, :email, :rg, :cpf, :address, :password, :password_confirmation, :current_password)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/show.html.erb
<h5 class="card-title text-center">Your Account</h5>
    
    <div class="form-label-group col-ms-4">
      <strong>Account number:</strong>
      <%= @account.account_number %>
    </div>

    <div class="form-label-group col-ms-6">
      <strong>Balance:</strong>
      <%= @account.balance %>
    </div>

    <div class="form-label-group col-ms-6">
      <strong>Customer:</strong>
      <%= @account.customer.full_name %>
    </div>
    <hr/>
    <%= render 'shared/operations' %>

app/views/layouts/application.html.erb
<<!DOCTYPE html>
<html>
  <head>
    <title>NobeBanking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href = "https://fonts.googleapis.com/icon?family=Material+Icons" rel = "stylesheet">
  </head>

  <body>
     <header>
          <%= render "shared/navbar"%>
     </header>

    <main>
      <div class="container-fluid">
        <div class="container">
          <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-6 mx-auto">
              <div class="card card-signin my-5">
                <div class="card-body">
                  <em class="alert-primary"><%= notice %></em>
                  <em class="alert-danger"<%= alert %></em>
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <div>
      <%= render "shared/footer" %>
    </div>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NobeBanking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <header>
          <%= render "shared/navbar"%>
     </header>

    <main>
      <div class="container-fluid">
        <div class="container">
          <div class="row">
            <div class="col-sm-10 col-md-12 col-lg-9 mx-auto">
              <div class="card card-signin my-5">
                <div class="card-body">
                  <em class="alert-primary"><%= notice %></em>
                  <em class="alert-danger"<%= alert %></em>
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <div>
      <%= render "shared/footer" %>
    </div>


    <%= javascript_pack_tag 'search', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/operations/_filter_form.html.erb
<%= search_form_for @search, url: search_operations_path, class: "form-inline", method: :post do |f| %>
  <div class="col-md-4">
    <%= f.text_field :created_at_gteq, class: "form-control", placeholder: "since", data: { behavior: "flatpickr" } %>
  </div>

  <div class="col-md-4">
    <%= f.text_field :created_at_lteq, class: "form-control", placeholder: "to the", data: { behavior: "flatpickr" } %>
  </div>

  <div class="col-md-2 col-md-offset-1 form-actions">
    <%= f.submit "Search", class: "btn btn-success" %>
  </div>
<% end %>

app/views/operations/index.html.erb
<h4>Bank statement</h4> 
<%= render 'filter_form' %>
<table class="table">
  <thead>
    <tr>
      <th>Kind</th>
      <th>Amount</th>
      <th>date</th>
      <th>Details</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |op| %>
      <tr>
        <td><%= op.kind %></td>
        <td><%= op.amount %></td>
        <td><%= op.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Show', op %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>
<br>
<%= link_to 'Back', root_path %>

app/views/operations/new_deposit.html.erb
  <h5 class="card-title text-center">New Deposit</h5>
  <%= form_for(@operation, url: deposit_path, class: "form-signin") do |f|%>
    <%= render 'shared/errors',obj: @operation %>
      <div>
        <%= f.hidden_field :account_id, value: @account.id%>
        <%= f.hidden_field :recipient, value: @account.account_number%>
        <%= f.hidden_field :kind, value: @kind%>
        <%= f.hidden_field :interest_rate, value: @interest_rate%>
      </div>
    
      <div class="form-label-group col-md-8">
          <%= f.number_field :amount, autofocus: true, autocomplete: "amount", 
                            class: "form-control", placeholder: "Amount"%><br />
          <%= f.label :amount%>
      </div>

    <div class="actions">
      <%= f.submit "Deposit", class: "btn btn-success btn-lg btn-primary"%>
    </div>
  <% end %>
    <%= link_to "Back",root_path %>

app/views/operations/new_transfer.html.erb
    <h5 class="card-title text-center">New Transfer</h5>
  <%= form_with model: @operation, url: transfer_path, class: "form-horizontal" do |f| %>
    <%= @errors %>
      <div>
        <%= f.hidden_field :account_id, value: @account.id%>
        <%= f.hidden_field :kind, value: @kind%>
        <%= f.hidden_field :interest_rate, value: @interest_rate%>
      </div>

  <div class="form-label-group col-md-8">
    <%= f.number_field :recipient, autofocus: true, autocomplete: "recipient", 
                     class: "form-control", placeholder: "" %><br />
    <%= f.label :recipient, "Account No" %>
  </div>

  <div class="form-label-group col-md-8">
    <%= f.text_field :amount, autofocus: true, autocomplete: "amount", 
                     class: "form-control", placeholder: "" %><br />
    <%= f.label :amount, "Amount to transfer", class: "control-label" %>
  </div>
  <div class="actions">
    <%= f.submit "Transfer", class: "btn btn-success btn-lg btn-primary btn-block" %>
  </div>
  <% end %>
  <%= link_to "Back",root_path %>

app/views/operations/new_withdraw.html.erb
  <h5 class="card-title text-center">Withdraw</h5>
<%= form_for(@operation, url: withdraw_path, class: "form-horizontal") do |f|%>
  <%= render 'shared/errors',obj: @operation %>
  <div>
    <%= f.hidden_field :account_id, value: @account.id%>
    <%= f.hidden_field :recipient, value: @account.account_number%>
    <%= f.hidden_field :kind, value: @kind%>
    <%= f.hidden_field :interest_rate, value: @interest_rate%>
  </div>
  
  <div class="form-label-group col-md-8">
    <%= f.number_field :amount, autofocus: true, autocomplete: "amount", 
                            class: "form-control", placeholder: "Amount"%>
    <%= f.label :amount%>
  </div>

  <div class="actions">
    <%= f.submit "Withdraw", class: "btn btn-success btn-lg btn-primary"%>
  </div>
  
<% end %>
    <%= link_to "Back",root_path %>

app/views/operations/show.html.erb
<h5 class="card-title text-center">Nobe Banking System</h5>

<div class="form-row">
  <div class="col-md-8"> Customer:</div>
  <div class="col-md-4"><b><%= @operation.account.customer.full_name %></b></div>
  
  <div class="col-md-8"> Account Number: </div>
  <div class="col-md-4"><b> <%= @operation.account.account_number %></b></div>

  <div class="col-md-8"> Operation: </div>
  <div class="col-md-4"> <b> <%= @operation.kind %> </b> </div>

  <div class="col-md-8"> Amount: </div>
  <div class="col-md-4"> <b> <%= @operation.amount %> </b> </div>

  <div class="col-md-8"> Rate: </div>
  <div class="col-md-4"> <b> <%= @operation.interest_rate %> </b> </div>
</div> 
<br />
<%= link_to "Back",root_path %>

app/views/pages/home.html.erb
<form class="form-horizontal">
<% if customer_signed_in? == false%>
  <h5 class="card-title text-center font-weight-light text-dark">Welcome Visitor</h5>
<% else %>
  <h5 class="card-title text-center font-weight-light text-dark">Welcome <%= current_customer.first_name %></h5>
  
<%end%> 
<hr>
</form>
<%= render 'shared/operations' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					<h5>prohibited this article from being saved:</h5>
				</h3>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<section class="copyright py-5 text-center text-light bg-transparent">
    <div class="container-fluid">
      <small class="m-0 text-center"><strong>Copyright &copy; Nobe_Banking 2020</strong></small>
    </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand-lg navbar-light bg-light border-bottom fixed-top">  
  <li class="navbar-brand">
    <%= link_to root_path do %>
      <%= image_tag "bank-logo", size: "30x30", class: "img-thumbnail"%>
    <% end %>
  </li>  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav d-none d-md-inline-block  ml-auto">
      <% if customer_signed_in? == false %>
        <li class="navbar-brand nav-item"><%= link_to 'Sign_in', new_customer_session_path, class: "nav-link" %></li>
        <li class="navbar-brand nav-item"><%= link_to 'Sign_up', new_customer_registration_path, class: "nav-link" %></li>
      <% else %>
          <li class="navbar-brand nav-item"><%= link_to "Profile", edit_customer_registration_path, class: "nav-link"%></li>
          <li class="navbar-brand nav-item"><%= link_to "My Account", current_customer.account, class: "nav-link"%></li>          
          <li class="navbar-brand nav-item"><%= link_to 'Logout', destroy_customer_session_path, class:"nav-link", method: :delete %></li> 
      <% end %>            
    </ul>
  </div>
</nav>

app/views/shared/_operations.html.erb
<div class="form-row">
  <div class="col-6">
   <%= link_to deposit_path do%>
     <%= image_tag "deposit", size: "100x100", class: "rounded float-center"%>  
   <% end %> 
  </div>
  <div class="col-6 col-sm-4">
    <%= link_to withdraw_path do%>
     <%= image_tag "withdraw", size: "100x100", class: "rounded float-right"%>
    <% end %>     
  </div>
</div>
<div class='form-row'>
  <div class="col-6">
    <%= link_to transfer_path do%>
      <%= image_tag "transfer", size: "100x100", class: "rounded float-left"%>
    <% end %>
  </div>

  <div class="col-6 col-sm-4">
    <%= link_to operations_path do%>
      <%= image_tag "bank_statement", size: "100x100", class: "rounded float-right"%>
    <% end %>
  </div>
</div>  